name: Deploy Web API to DigitalOcean

on:
  push:
    paths:
      - 'Foosify.Api/**'  # Only trigger when the API code changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t foosify-api:latest ./Foosify.Api

      - name: Save Docker image as tar file
        run: docker save foosify-api:latest -o foosify-api.tar

      - name: Copy image to DigitalOcean
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          source: foosify-api.tar
          target: /root/

      - name: SSH into DigitalOcean and load image
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            docker load -i /root/foosify-api.tar
            docker stop foosify-api-container || true
            docker rm foosify-api-container || true
            docker run -d --name foosify-api-container foosify-api:latest
