# Workflow to deploy the FoosballProLeague API to DigitalOcean

on:
  # Trigger the workflow on pushes to the 'main' branch that modify files in the API project directory
  push:
    branches:
      - main
#    paths:
#      - 'FoosballProLeague.Api/**'

jobs:
  # Step 1: Build and test the project
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1.1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1.2: Set up the .NET environment with the specified version
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # Step 1.3: Restore project dependencies
      - name: Restore dependencies
        run: dotnet restore FoosballProLeague.Api/FoosballProLeague.Api/FoosballProLeague.Api.csproj

      # Step 1.4: Build the project in Release configuration
      - name: Build project
        run: dotnet build FoosballProLeague.Api/FoosballProLeague.Api/FoosballProLeague.Api.csproj --configuration Release

      # Step 1.5: Create a test-specific configuration file for running tests
      - name: Create appsettings.test.json
        run: |
          echo '{
            "ConnectionStrings": {
              "DatabaseConnection": "${{ secrets.TEST_DATABASE_CONNECTION }}"
            },
            "ApiKey": "very_secure_api_key",
            "Jwt": {
              "SigningKey": "very_secure_signing_key_that_is_long_enough"
            }
          }' > FoosballProLeague.Api/FoosballProLeague.Api.Tests/appsettings.test.json

      # Step 1.6: Run the unit tests for the project
      - name: Run tests
        run: dotnet test FoosballProLeague.Api/FoosballProLeague.Api.Tests/FoosballProLeague.Api.Tests.csproj --verbosity normal

  # Step 2: Deploy the application
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Step 2.1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2.2: Set up Docker Buildx for building images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 2.3: Build the Docker image for the application
      - name: Build Docker Image
        run: docker build -t foosballproleague-api:latest ./FoosballProLeague.Api

      # Step 2.4: Save the Docker image as a tar file for transfer
      - name: Save Docker image as tar file
        run: docker save foosballproleague-api:latest -o foosballproleague-api.tar

      # Step 2.5: Set appropriate permissions for the tar file
      - name: Set permissions for TAR file
        run: chmod 755 foosballproleague-api.tar

      # Step 2.6: Perform pre-deployment cleanup on the DigitalOcean server
      - name: Pre-deployment cleanup on DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            echo "Performing pre-deployment cleanup..."
            if [ -f /root/foosballproleague-api.tar ]; then
              echo "Existing tarball found. Removing it."
              rm -f /root/foosballproleague-api.tar
            fi
            docker stop foosballproleague-api-container || true
            docker rm foosballproleague-api-container || true
            docker rmi foosballproleague-api:latest || true

      # Step 2.7: Transfer the Docker image tar file to the server
      - name: Copy image to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          source: "foosballproleague-api.tar"
          target: "/root/"

      # Step 2.8: Debug the file transfer and Docker images on the server
      - name: Debug file transfer and Docker images on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            echo "Checking if tarball exists and its size..."
            if [ -f /root/foosballproleague-api.tar ]; then
              echo "Docker image tarball found at /root/foosballproleague-api.tar"
              ls -lh /root/foosballproleague-api.tar
            else
              echo "Docker image tarball not found!"
              exit 1
            fi

            echo "Debugging files in /root directory:"
            ls -l /root

            echo "Debugging Docker images before loading:"
            docker images

            echo "Loading the Docker image..."
            docker load -i /root/foosballproleague-api.tar

            echo "Debugging Docker images after loading:"
            docker images

      # Step 2.9: Deploy the Docker image by running it as a container
      - name: Deploy Docker image on DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            docker load -i /root/foosballproleague-api.tar
            echo "Stopping any existing containers..."
            docker stop foosballproleague-api-container || true
            docker rm foosballproleague-api-container || true
            echo "Running new container..."
            docker run -d -p 5001:5001 \
            --name foosballproleague-api-container \
            -e ConnectionStrings__DatabaseConnection="${{ secrets.DATABASE_CONNECTION_STRING }}" \
            -e ApiKey="${{ secrets.X_API_KEY }}" \
            -e Jwt__SigningKey="${{ secrets.JWT_SIGNING_KEY }}" \
            foosballproleague-api:latest

      # Step 2.10: Clean up the tar file from the server post-deployment
      - name: Post-deployment cleanup on DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            echo "Cleaning up tarball from the server..."
            rm -f /root/foosballproleague-api.tar
